### ISSUE TITLE
WebType и WebLogic

### ISSUE THREAD

**Issue by olgaklimenko** [gKrokod/webServer#14]
1. Нужно отрефакторить файл WebType:

1) Квери положить отдельно
2) Разделить типы для входных/выходных данных на файлы по отношению к сущностям
3) WebType слишком широкое название, для типов, которые мы получаем от юзера и отправляем юзеру. Можно назвать UserData, APIData, DTO или что-то такое. DTO - это Data Transfer Object, это общепринятое название для типов, которые используются для общения с другими приложениями, фронтом, пользователем. Тут слово Object не должно смущать как что-то из ООП, это слово тут больше для объединения данных в одну структуру, так что можно вместо него представлять cлово Data. 

https://www.reddit.com/r/functionalprogramming/comments/1b6yzuv/how_are_functional_programming_paradigms/

2. WebLogic не содержит никакой логики, а больше утилитарные функции, что обманывает ожидания). Думаю их можно назвать WebUtils, или как-то так.

**Comment by gKrokod** [comment]
done

**Comment by gKrokod** [comment]
done
