### ISSUE TITLE
Небезопасный код и частичные функции

### ISSUE THREAD

**Issue by roman-bodavskiy** [gKrokod/webServer#7]
https://github.com/gKrokod/webServer/blob/main/src/Database/Data/FillTables.hs#L27

`read $(localtimeTemplate)`
С одной стороны это используется только в тестовых данных. С другой стороны тут частично определенная функция, и IO вызывается внутри шаблона, выглядит не очень безопасно

@olgaklimenko мы можем пропустить такой код?

**Comment by olgaklimenko** [comment]
У нас чёткое требование, чтобы partial functions не было: https://github.com/fullstack-development/haskell-internship/blob/master/review-task.md. Так что надо исправлять.

**Comment by olgaklimenko** [comment]
Статья про проблемы, которые могут появится из-за использования нетотальных функций:
https://kowainik.github.io/posts/totality

В тестах использование может привести к тому, что будешь долго искать откуда эта неявная ошибка вылезла и возможно сначала полезешь в код, а не в сами тесты. Поэтому тесты - это не аргумент)
